# Generated by Django 4.1.3 on 2023-06-17 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonLabels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.IntegerField(default=0)),
                ('cat_name', models.CharField(max_length=64)),
                ('svg_str', models.CharField(default='nothing', max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='HuggingFaceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_path', models.CharField(max_length=200)),
                ('upd_date', models.DateTimeField(verbose_name='date updated')),
            ],
        ),
        migrations.CreateModel(
            name='ModelInfor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_los', models.DecimalField(decimal_places=12, max_digits=15)),
                ('train_acc', models.DecimalField(decimal_places=12, max_digits=15)),
                ('val_los', models.DecimalField(decimal_places=12, max_digits=15)),
                ('val_acc', models.DecimalField(decimal_places=12, max_digits=15)),
                ('test_los', models.DecimalField(decimal_places=12, max_digits=15)),
                ('test_acc', models.DecimalField(decimal_places=12, max_digits=15)),
                ('model_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='final_lab.huggingfacemodel')),
            ],
        ),
        migrations.CreateModel(
            name='AmazonProductReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewText', models.CharField(max_length=1500)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='final_lab.amazonlabels')),
            ],
        ),
    ]
